### PR TITLE
Clean main.nf

### PR DESCRIPTION
**Pull request by jylee-bcm**
I would like to clean a little bit about the `main.nf`.

- [x] Separate functions from processes
- [x] Use named outputs

Feel free to feedback the changes!

### CODE REVIEW

**Review by hyunhwan-bcm — APPROVED** [review]

**Comment by ZaahidShaik** [comment]
Can you run these cmd's and add the output in the PR details section. To verify you changes.


1. Checking help.
```
nextflow run main.nf --help
```

2. Checking the error are working fine. Just give the same VCF file path as input in both `--input-vcf` & `--input-hpo` or any non '.txt' / 'hpo' files. You should get these errors. 

```
Error: '--input_hpo' value '/home/sample/sample.vcf.gz' should be an HPO file (.hpo) or (.txt)

  To see usage and available parameters run `nextflow run main.nf --help`
```

**Comment by ZaahidShaik** [comment]
Verified in person with @jylee-bcm, Approving!

**Review by ZaahidShaik — APPROVED** [review]

**Comment by jylee-bcm** [comment]
@ZaahidShaik @hyunhwan-bcm Thank you for reviewing, but I added one thing more regarding named output. I would like to get your approval once again!

**Comment by jylee-bcm** [comment]
Oh! haha.. already merged. Thanks!

**Pull request merged**
