### PR TITLE
edit dockerfile for automatical bedtools/bcftools installation.

### PR DESCRIPTION
**Pull request by hyunhwan-bcm**
related to #25

### CODE REVIEW

**Comment by arine** [comment]
Need to update [Installation Doc](https://github.com/LiuzLab/AI_MARRVEL/blob/main/docs/source/installation.rst)

**Comment by SpicyChicken6** [comment]
Do you mind checking on this edit again? I think the bedtools installed this way couldn't work in docker, probably need to move bedtools to a different folder within docker: 
```
# Install bedtools
RUN wget https://github.com/arq5x/bedtools2/releases/download/v2.30.0/bedtools.static.binary \
    && mv bedtools.static.binary /usr/local/bin/bedtools 
```

Thank you,

**Comment by hyunhwan-bcm** [comment]
`bedtools` used like this way:

https://github.com/LiuzLab/AI_MARRVEL/blob/0c6e6f15c5a14584e7e4527732c880bbf4b53696/run/simple_repeat_anno.py#L17

so basically it doesn't break anything. Thanks for checking

**Comment by SpicyChicken6** [comment]
> `bedtools` used like this way:
> 
> https://github.com/LiuzLab/AI_MARRVEL/blob/0c6e6f15c5a14584e7e4527732c880bbf4b53696/run/simple_repeat_anno.py#L17
> 
> so basically it doesn't break anything. Thanks for checking

 Sorry I didn't check on the use of it.  Thanks Hwan!

**Pull request merged**
